name: ozzen
description: Ozzen mobile app
publish_to: none

version: 2.21.6+248

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_maps_webservice: 0.0.20-nullsafety.5
  http: 1.2.0
  timeago: 3.6.0

dependency_overrides:
  http: 1.2.0