name: ozzen
description: Ozzen mobile app
publish_to: none

version: 2.21.6+248

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  share_plus: 7.2.1
