name: ozzen
description: Ozzen mobile app
publish_to: none

version: 2.21.6+248

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: 2.0.11
  firebase_core: 2.24.2
  firebase_auth: 4.16.0 
  firebase_dynamic_links: 5.4.8
  firebase_remote_config: 4.3.8
  firebase_storage: 11.6.0
  random_string: 2.3.1
  timeago: 3.6.0
  convert: 3.1.1
  intl: 0.19.0
  image_picker: 1.0.7
  photo_view: 0.14.0
  image_cropper: 5.0.1
  google_maps_webservice: 0.0.20-nullsafety.5
  google_mlkit_barcode_scanning: 0.10.0
  google_mlkit_commons: 0.6.1
  url_launcher: 6.2.3
  reorderables: 0.6.0
  uuid: 4.3.3
  checkdigit: 0.3.1
  flutter_platform_widgets: 6.0.2
  cupertino_icons: 1.0.6
  http: 1.2.0
  share_plus: 7.2.1
  intercom_flutter: 8.0.8
  contacts_service: 0.6.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  permission_handler: 11.2.0
  flutter_cache_manager: 3.3.1
  connectivity_plus: 5.0.2
  flutter_riverpod: 2.4.9
  collection: 1.18.0
  dotted_border: 2.1.0
  badges: 3.1.2
  file_picker: 6.1.1
  flutter_genius_scan: 4.21.0
  open_filex: 4.3.4
  sentry: 7.14.0
  sentry_flutter: 7.14.0
  gql: 1.0.0+1
  flutter_inappwebview: 6.0.0
  responsive_builder: 0.7.0
  url_strategy: 0.2.0
  beamer: 1.6.0
  path: 1.8.3
  flutter_dropzone: 3.0.6
  platform: 3.1.4
  pinput: 3.0.1
  device_preview: 1.1.0
  map_launcher: 3.1.0
  signature: 5.4.1
  meta: 1.10.0
  meilisearch: 0.15.0
  path_provider: 2.1.2
  wakelock: 0.6.2
  universal_html: 2.2.4
  local_auth: 2.1.8
  local_auth_android: 1.0.36
  local_auth_ios: 1.1.6
  flutter_markdown: 0.6.18+3
  package_info_plus: 5.0.1
  flutter_branch_sdk: 6.8.0
  flutter_svg: 2.0.9
  appsflyer_sdk: 6.12.2
  advertising_id: 2.6.0
  fl_chart: 0.66.0
  lazy_load_indexed_stack: 1.1.0
  camera: 0.10.5+9
  

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: 3.0.1
  flutter_launcher_icons: 0.13.1
  build_runner: 2.4.8
  flutter_native_splash: 2.3.9
  hive_generator: 2.0.1
  sentry_dart_plugin: 1.6.3

dependency_overrides:
  gql: 1.0.0+1
  intl:  0.19.0
  win32: 3.1.4
  http: 1.2.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: images/logomark.png
  android12: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "images/icon_android@1024.png"
  image_path_ios: "images/icon_ios@1024.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/
    - langs/

sentry:
  upload_source_maps: true
  upload_sources: true
  project: iris
  org: ozzen
  wait_for_processing: true
  commits: true
  ignore_missing: true
  
